version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bookmark-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookmark_manager
      POSTGRES_USER: bookmark_user
      POSTGRES_PASSWORD: bookmark_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bookmark_user -d bookmark_manager']
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-test:
    image: postgres:15-alpine
    container_name: bookmark-db-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookmark_manager_test
      POSTGRES_USER: bookmark_user
      POSTGRES_PASSWORD: bookmark_password
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bookmark_user -d bookmark_manager_test']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
